include("header.jl")

@testset "math" begin
    @test randcheck(acos,cos)
    @test randcheck(acosd,cos)
    @test randcheck(acosh,cosh)
    @test randcheck(acot,cot)
    @test randcheck(acotd,cot)
    @test randcheck(acoth,coth)
    @test randcheck(acsc,csc)
    @test randcheck(acscd,csc)
    @test randcheck(acsch,csch)
    @test randcheck(asec,sec)
    @test randcheck(asecd,sec)
    @test randcheck(asech,sech)
    @test randcheck(asin,sin)
    @test randcheck(asind,sin)
    @test randcheck(asinh,sinh)
    @test randcheck(atan,tan)
    @test randcheck(atand,tan)
    @test randcheck(atanh,tanh)
    @test randcheck(cbrt)
    @test randcheck(clamp,identity,xargs=(-0.5,0.5))
    #@test randcheck(clamp!) # overwrites
    @test randcheck(cos)
    @test randcheck(cosc)
    @test randcheck(cosd)
    @test randcheck(cosh)
    @test randcheck(cospi)
    @test randcheck(cot)
    @test randcheck(cotd)
    @test randcheck(coth)
    @test randcheck(csc)
    @test randcheck(cscd)
    @test randcheck(csch)
    @test randcheck(deg2rad)
    @test randcheck(exp)
    @test randcheck(exp10)
    @test randcheck(exp2)
    @test randcheck(expm1)
    @test randcheck(exponent)
    #@test randcheck(frexp) # returns 2 values
    @test randcheck(hypot,identity,identity)
    @test randcheck(ldexp,identity,xargs=(rand(-5:5),))
    @test randcheck(log,exp)
    @test randcheck(log,exp,exp)
    @test randcheck(log10,exp)
    @test randcheck(log1p,exp)
    @test randcheck(log2,exp)
    @test randcheck(max,identity,identity)
    @test randcheck(min,identity,identity)
    #@test randcheck(minmax) # returns 2 values
    @test randcheck(mod2pi)
    #@test randcheck(modf)   # returns 2 values
    @test randcheck(rad2deg)
    @test randcheck(rem2pi,identity,xargs=(RoundNearest,))
    @test randcheck(sec)
    @test randcheck(secd)
    @test randcheck(sech)
    @test randcheck(significand)
    @test randcheck(sin)
    @test randcheck(sinc)
    #@test randcheck(sincos) # returns 2 values
    @test randcheck(sind)
    @test randcheck(sinh)
    @test randcheck(sinpi)
    @test randcheck(sqrt,abs2)
    @test randcheck(tan)
    @test randcheck(tand)
    @test randcheck(tanh)
end

