include("gradcheck.jl")

mathcheck(f,t=identity)=(g(x)=f.(x); gradcheck(f,t(randn())) && gradcheck(g,t.(randn(2))))

@testset "math" begin
    @test mathcheck(acos,cos)
    @test mathcheck(acosd,cos)
    @test mathcheck(acosh,cosh)
    @test mathcheck(acot,cot)
    @test mathcheck(acotd,cot)
    @test mathcheck(acoth,coth)
    @test mathcheck(acsc,csc)
    @test mathcheck(acscd,csc)
    @test mathcheck(acsch,csch)
    @test mathcheck(asec,sec)
    @test mathcheck(asecd,sec)
    @test mathcheck(asech,sech)
    @test mathcheck(asin,sin)
    @test mathcheck(asind,sin)
    @test mathcheck(asinh,sinh)
    @test mathcheck(atan,tan)
    @test mathcheck(atand,tan)
    @test mathcheck(atanh,tanh)
    @test mathcheck(cbrt)
    #@test mathcheck(x->clamp(x,-1,1))
    #@test mathcheck(clamp!)
    @test mathcheck(cos)
    @test mathcheck(cosc)
    @test mathcheck(cosd)
    @test mathcheck(cosh)
    @test mathcheck(cospi)
    @test mathcheck(cot)
    @test mathcheck(cotd)
    @test mathcheck(coth)
    @test mathcheck(csc)
    @test mathcheck(cscd)
    @test mathcheck(csch)
    @test mathcheck(deg2rad)
    @test mathcheck(exp)
    @test mathcheck(exp10)
    @test mathcheck(exp2)
    @test mathcheck(expm1)
    @test mathcheck(exponent)
    #@test mathcheck(frexp)
    #fail @test mathcheck(hypot)
    #fail @test mathcheck(ldexp)
    @test mathcheck(log,exp)
    #fail @test mathcheck(log) # 2arg
    @test mathcheck(log10,exp)
    @test mathcheck(log1p,exp)
    @test mathcheck(log2,exp)
    #@test mathcheck(max)
    #@test mathcheck(min)
    #@test mathcheck(minmax)
    @test mathcheck(mod2pi)
    #@test mathcheck(modf)
    @test mathcheck(rad2deg)
    #@test mathcheck(rem2pi)
    @test mathcheck(sec)
    @test mathcheck(secd)
    @test mathcheck(sech)
    @test mathcheck(significand)
    @test mathcheck(sin)
    @test mathcheck(sinc)
    #@test mathcheck(sincos)
    @test mathcheck(sind)
    @test mathcheck(sinh)
    @test mathcheck(sinpi)
    @test mathcheck(sqrt,abs2)
    @test mathcheck(tan)
    @test mathcheck(tand)
    @test mathcheck(tanh)
end

